version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: chore_app_postgres
    environment:
      POSTGRES_DB: chore_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/initial_data.sql:/docker-entrypoint-initdb.d/initial_data.sql

volumes:
  postgres_data: